### ISSUE TITLE
Internet availability may not be being verified in project

### ISSUE THREAD

**Issue by amazuerar** [nvllsvm/Audinaut#109]
Dear Developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified that there is a missing validation of Internet availability within the project which is needed since some network operations are being performed in the application. 

As you might know, a device may be connected to a network but may not have Internet connection. Therefore it is recommended for the app to identify whether the device is connected to a network having Internet connectivity before performing a network operation.

In order to address this issue we recommend you to visit:

1. https://developer.android.com/reference/android/net/NetworkCapabilities
2. https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_INTERNET
3. https://developer.android.com/reference/android/net/NetworkCapabilities#NET_CAPABILITY_VALIDATED

**Comment by nvllsvm** [comment]
Internet connectivity is not necessarily required as the destination server may be available on the local network.
