### ISSUE TITLE
Only one album shows up in the library

### ISSUE THREAD

**Issue by paride** [nvllsvm/Audinaut#13]
When I update the library only one album shows up. This doesn't happen with the (rather old) DSub app available in F-Droid. I'm running Libresonic 6.2beta3. The library contains 3 albums from 3 different artists.

**Comment by nvllsvm** [comment]
In DSub, are you browsing by tags or file structure? See below:
![screenshot_1492726941](https://cloud.githubusercontent.com/assets/6550543/25254982/877d6bbc-25f6-11e7-8ff3-9b75abab1368.png)

**Comment by paride** [comment]
I was browsing by file structure. If I browse "by tags" I get the same problem even with DSub. So I guess it's not Audinaut's fault...

**Comment by nvllsvm** [comment]
Correct - this feature was explicitly removed when Audinaut was forked from DSub.

This functionality should be transparent to the clients. Unfortunately, the Subsonic/Libresonic API is kind of terrible and should be rewritten for greater flexibility.
