### ISSUE TITLE
Opinionated build

### ISSUE THREAD

**Issue by vvug** [nvllsvm/Audinaut#14]
Dello @nvllsvm, could you please elaborate a bit more on what you mean by "opinionated build"? Is it only on licensing (avoiding proprietary libraries)? Is there anything else? It would be great if you could be more specific in the README.

Thanks for this great app!

**Comment by nvllsvm** [comment]
The Libresonic/Subsonic API contains a lot of bullshit I don't plan on suppporting (ex. chat). Thus, opinionated.

Since I can't quantify what exactly that means, I've removed it for the time being.
