### ISSUE TITLE
Cannot launch Audinaut due to "Format specifier" error message

### ISSUE THREAD

**Issue by r0bbie** [nvllsvm/Audinaut#2]
On downloading and installing the latest provided Audinaut apk (v0.1.0), on launching the app I immediately receive a "Format specifier: 2$s" error message.

If this is dismissed a "uid 10227 cannot explicitly add accounts of type: subsonic.org" error message is then displayed. There is no way to dismiss this message as it repeatedly appears, so the app is currently unusable.

Screenshots below:

<img src="https://cloud.githubusercontent.com/assets/1804229/23463315/eb336b7e-fe88-11e6-8a3a-37970b8b51ec.png" width="250">

<img src="https://cloud.githubusercontent.com/assets/1804229/23463314/eb2cf398-fe88-11e6-964a-5ad6227a6678.png" width="250">

**Comment by craftyguy** [comment]
I also get this after installing audinaut from f-droid.

**Comment by knutztar** [comment]
I've had the exact same problem after installing from f-droid. 
I tried uninstalling DSub because I suspected that it would clash somehow with that app having the same account type. I still got the "Format specifier" error but it fixed the "account type" error.

**Comment by craftyguy** [comment]
I found the issue, which is [here at line 760 in SubsonicFragmentActivity.java ](https://github.com/nvllsvm/Audinaut/blob/master/app/src/main/java/net/nullsum/audinaut/activity/SubsonicFragmentActivity.java#L760). DSub supports resuming playback from a remote device, and so there's a dialog where it asks if you'd like to resume but your version of this file does not supply the second argument for constructing the 'common_confirm_message' string (second argument is a string asking "do you want to resume"). 

The fix can have several forms, depending on what Audinaut is capable of:

1) if it supports remote playback and resume like DSub, then just need to add a string in strings.xml and modify line 760 so something like:

````
    String message = getResources().getString(R.string.common_confirm_message,
                              getResources().getString(R.string.download_restore_play_queue).toLowerCase(), Util.formatDate(remoteState.changed)); 
````

2) If it doesn't support this feature, then the whole promptRestoreFromRemoteQueue function in SubsonicFragmentActivity can be ripped out.

@nvllsvm, how would you like to handle this?

**Comment by nvllsvm** [comment]
@craftyguy My needs for a Libresonic app are relatively simple, so I've removed promptRestoreFromRemoteQueue. 

My general attitude with this fork is to remove extra cruft and recode later if it's desired.

**Comment by craftyguy** [comment]
No problem, I'm glad you made this fork and just trying to help!
