### ISSUE TITLE
Google Cast support?

### ISSUE THREAD

**Issue by jpsutton** [nvllsvm/Audinaut#20]
Are there any plans to add Google Cast / Chromecast support to Audinaut?  If there wasn't already an effort underway, and no on opposes it, I was going to attempt to fork, add, and submit a pull request.

**Comment by nvllsvm** [comment]
Google Cast / Chromecast support requires proprietary Google libraries. This goes against the FOSS spirit of Audinaut. It was explicitly removed when Audinaut was forked from [DSub](https://github.com/daneren2005/Subsonic).

Sounds like DSub is the client you're looking for as it comes with Chromecast support already.

**Comment by jpsutton** [comment]
Fair enough.  Thanks.
