### ISSUE TITLE
Crashes on launch on Lollipop

### ISSUE THREAD

**Issue by muhammadarif1** [nvllsvm/Audinaut#23]
#### Expected behavior
this application should be open and listen to music online with the help of libresonic
#### Actual behavior
I tried to open this app and try to listen to music online. this application even stops itself and failed to open.
#### How to reproduce
-download the app

-lauch the app and the app get crashed 
* Operating system: advan s5e nxt android lolipop idos 5.1

app version; o.2.3 
#### Recording Of The Bug
https://www.youtube.com/watch?v=to5imuZq2B4

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@muhammadarif/audinaut-app-get-crased-when-try-to-open-the-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by MasaruKato** [comment]
I've experienced the same issue on my phone.

**Comment by nvllsvm** [comment]
@MasaruKato  - What phone and OS version are you running?

**Comment by nvllsvm** [comment]
Fixed in https://github.com/nvllsvm/Audinaut/releases/tag/0.2.4
