### ISSUE TITLE
Add support for Android Auto

### ISSUE THREAD

**Issue by the1poet** [nvllsvm/Audinaut#34]
I am currently using DSUB (which I'm assuming this is forked from?)
It works, but it hasn't been updated in quite some time.
I was wondering if you have any plans for adding Android Auto support for your app?

**Comment by nvllsvm** [comment]
Yes, this is a fork of DSub.

Android Auto won't be added as I want to keep Audinaut strictly free software.

**Comment by the1poet** [comment]
Is there a licencing fee or something I'm not aware of with Android Auto?

**Comment by nvllsvm** [comment]
No - it's just a proprietary application.

**Comment by RDLeatherwood** [comment]
Any chance this will be revisited? Maybe make a premium version with android auto?  Dsub has been buggy and I'd rather move to something else.
