### ISSUE TITLE
Use query parameters instead of body

### ISSUE THREAD

**Issue by drolsquito** [nvllsvm/Audinaut#37]
Hi, I was looking for an alternative to dsub and found Audinaut on F-Droid.
The problem is that I can't connect to my servers, I can see music artists but when I click on an artist I get the message: "Error - required parameter "id" not present"

I see that there's no "Browse by Tags" option, with this option enabled on dsub everything works fine, will you implement this option it in the future ?

Thank you

**Comment by nvllsvm** [comment]
The option was enabled by default when I removed it. What server and server version are you running?

**Comment by drolsquito** [comment]
I'm trying to run a Funkwhale instance (https://open.audio/) with Audinaut v0.3.2 from F-Droid.
A friend has the same issue with his instance, it works only with the "Browse by Tags" option in DSub or UltraSonic. So you are saying the option is not visible but it's enabled by default ? Maybe I'm wrong but seems not.

**Comment by nvllsvm** [comment]
Audinaut only uses the tag-based endpoints for browsing. I'll do some testing with Funkwhale.

**Comment by taohansen** [comment]
What's the status on this? I, too, am running a Funkwhale instance and am encountering this bug.

**Comment by dddddd-mmmmmm** [comment]
I'm working on getting Audinaut working with Funkwhale. I've got the library/cover art working and will get audio working when I get the chance.

**Comment by nvllsvm** [comment]
Thanks @dddddd-mmmmmm !
