### ISSUE TITLE
Fdroid integration

### ISSUE THREAD

**Issue by jooola** [nvllsvm/Audinaut#4]
This fork is great ! Really good idea ! have to keep this up !

I'm already posting a issue about fdroid ! Well the app need to be in the fdroid repo.
As far a i now dsub couldn't build after Dsub-5.0.3 on the fdroid repo.

If we could make this work that would be awesome !

**Comment by nvllsvm** [comment]
Refresh your repositories in F-Droid. As of today, it's available for download.
