### ISSUE TITLE
[Android] connection failure even with the demo server

### ISSUE THREAD

**Issue by z-vap** [nvllsvm/Audinaut#50]
I wanted to use tis  but it fails to connect.   Even the default subsonic demo fails to connect.  I installed airsonic in a docker container.   Then I downloaded this to my android phone.  Other apps  (ultrasonic) connect fine but this fails to connect to my airsonic server and to the subsonic server.   

I am using the latest android on a moto x4.

**Comment by generaleramon** [comment]
I think i have the same problem. v0.3.2 works, v0.3.3 gives me a connection error.

**Comment by nvllsvm** [comment]
Please provide the following:
* Device model
* Numeric Android version (ex. 9.0)

If possible, please provide logcat output (https://developer.android.com/studio/command-line/logcat)

**Comment by generaleramon** [comment]
Xiaomi MI 8 (dipper)
Android 9.0 (last LineageOS 16 build)
[logcat_08-08-2019_09-37-06.txt](https://github.com/nvllsvm/Audinaut/files/3480426/logcat_08-08-2019_09-37-06.txt)

**Comment by generaleramon** [comment]
Motorola G5
Android 7.1 (Lineage 14.1)
Working fine with v0.3.3

**Comment by dddddd-mmmmmm** [comment]
`[08-08 09:36:56.208 8135:8159 E/SelectRecyclerFragment]
Failed to load
java.net.UnknownServiceException: CLEARTEXT communication to generaleramon.ddns.net not permitted by network security policy
	at net.nullsum.audinaut.service.RESTMusicService.getIndexes(RESTMusicService.java:123)
	at net.nullsum.audinaut.service.CachedMusicService.getIndexes(CachedMusicService.java:115)
	at net.nullsum.audinaut.fragments.SelectArtistFragment.getObjects(SelectArtistFragment.java:171)
	at net.nullsum.audinaut.fragments.SelectRecyclerFragment$UpdateTask.doInBackground(SelectRecyclerFragment.java:185)
 **snip**`

Looks like your ddns setup is setup to not allow plain HTTP connections.

**Comment by SenorSmartyPants** [comment]
This is happening to me as well. http traffic to latest airsonic and demo server don't connect.

Moto g7
Android 9

**Comment by generaleramon** [comment]
i guess commit 9e57cf1 fix the problem in Android 9

**Comment by SenorSmartyPants** [comment]
All we need now is a new release then.

**Comment by nvllsvm** [comment]
Fixed in 0.4.0
