### ISSUE TITLE
is there a timeout on getArtists?

### ISSUE THREAD

**Issue by lachlan-00** [nvllsvm/Audinaut#51]
I used to have a proxytimeout of 15 seconds for my apache/php-fpm/ampache server but i noticed i was failing to get my artist list in that time.

I've extended that and can manually get my url in firefox but audinaut times out.
![image](https://user-images.githubusercontent.com/1305249/65294000-87bbe880-dba0-11e9-9603-b0936ea0df9b.png)

Is there a hard limit in the client for api calls?

**Comment by dddddd-mmmmmm** [comment]
I believe Settings > Cache/Network > Network Timeout should work.

**Comment by lachlan-00** [comment]
that's it!
