### ISSUE TITLE
Library: no data (timeout?)

### ISSUE THREAD

**Issue by robertkrause** [nvllsvm/Audinaut#71]
When I connect to my subsonic server and select Library, it tries only for a few seconds and then displays "no data". Subsonic runs on an Odroid C1+ (not very powerful) and the music collection is large (>20000 titles), therefore it will take a while to load the library. Can Audinaut be modified to increase the wait time or maybe make it a settings option?

**Comment by simao** [comment]
There is already a `Network Timeout` in `Settings -> Cache/Network`. This does not help you?

**Comment by n1trob4ct3r** [comment]
I am having the same issue. I have tried setting `Network Timeout` to the maximum value of `60` seconds but it still doesn't work. I can see the library with no problems when I open in browser. What is happening here ? Is there any way to fix this ?
I have been using Subsonic and it works perfectly fine there but I want to switch to Audinaut.

**Comment by robertkrause** [comment]
I have also set this Network Timeout to the maximum (60 Seconds). Still the library loading gives up after 10 Seconds with "no data".
